### ISSUE TITLE
Model conversion to ctm

### ISSUE THREAD

**Issue by katjaq** [Cecropia/thehallaframe#10]
Hello! Thank you very much for providing this fantastic project ! It is super nice and fun, and we wanted to try putting our own models into the gallery :) However, I cannot seem to obtain correct `.ctm` models that would load the model plus my texture in your gallery (model loaded either glowing white or black, although `_tex.jpg` is provided). I tried going back to display your provided lion from its `.obj` file, but this renders a glowing white lion, same as my own models. So, it seems it needs to be `.ctm`.

As workflow you mention "models are exported individually, converted to CTM". Which format do you export from blender? And how did you convert these to `.ctm`?

Thank you very much for your help.
Best, Katja

**Comment by Absulit** [comment]
Hi @katjaq, thank you for trying our project.

I will try to answer your questions the best I can.
The models originally are OBJ exported from Blender and converted to CTM with this program http://openctm.sourceforge.net/, its a command-line program and you have to use a Terminal to run it, it's something like this:

`ctmconv.exe infile outfile [options]`

as for the textures, they are/will probably not work with your models because the CTM component is custom and it searches for the textures inside the /textures directory, and it uses a `name` property on the a-entity ctm tag (https://github.com/Cecropia/thehallaframe/blob/master/index.html#L256), the .jpg extension is expected. You can check the specific line from the component that loads the image here: https://github.com/Cecropia/thehallaframe/blob/master/js/ctm_component.js#L28

But you should be able to load your own OBJ models, check the following lines:

https://github.com/Cecropia/thehallaframe/blob/master/index.html#L157


        
        
        <a-asset-item id="lion-ctm" src="models/lion.ctm"></a-asset-item>
        
        

as you can see here on these previous lines, the lines (just in case you didn't know, but I guess you do) starting with `<!--` and ending with `-->` are "comments" or in a way "inactive code" so you can delete the `a-asset-item` that loads the lion.ctm asset, and remove the `<!--` and `-->` from the lion.obj and lion.jpg

And there's another piece of code you should modify here:

https://github.com/Cecropia/thehallaframe/blob/master/index.html#L256

      
      <a-entity ctm="src: #lion-ctm; name:lion;"></a-entity>

you have to delete the a-entity ctm and uncomment the a-entity obj-model that enables the obj model.

And I think this is all you need, you can use CTM for better compression and file size or you can use the OBJs. Actually the OBJs are standard A-Frame documentation, you can check their documentation on a better explanation on how to load your OBJ models here: https://aframe.io/docs/1.0.0/primitives/a-obj-model.html

Thanks again for using the project, and if you have more questions, please let us know.
